import { compile } from "json-schema-to-typescript";
import schema from "./schema.json" with { type: "json" };

if (import.meta.main) {
  // deno-lint-ignore no-explicit-any
  const result = await compile(schema as any, "", {
    "bannerComment": `// deno-fmt-ignore
// This file is automatically generated from generator.ts`,
  });

  Deno.writeTextFile(new URL(import.meta.resolve("./types.ts")), result);
}
